### ISSUE TITLE
Reset the font

### ISSUE THREAD

**Issue by suhani1804** [suhani1804/meet-clone#3]

**Comment by real-coder007Ravi** [comment]
I want to work on this issue. Could u please assign it to me

**Comment by harsh0853** [comment]
Hey can you please elaborate which type of font you want ?

**Comment by real-coder007Ravi** [comment]
I can use Helvetica font here. It might look different and good

**Comment by suhani1804** [comment]
https://meet.google.com/ You can refer the real website
